Update ArrayStack.php
Array object cannot be defined twice, this is a minor typo because it is not the php ArrayObject that is needed in this, but the Stdlib\ArrayObject.




stack call:
Fatal error: Cannot use ArrayObject as ArrayObject because the name is already in use




error is found with the 
skeleton application
doctrine module
doctrine orm module
doctrine dbal

Rectified the error from my last pull request